name: test
on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.json'
      - '**.yml'
  pull_request:
    paths:
      - '!*.md'
jobs:
  test:
    strategy:
      matrix:
        # platform: [ windows-latest, macOS-latest ]
        platform: [ ubuntu-latest ]
        node: [ '16.13.0' ]
    name: test/node ${{ matrix.node }}/${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.13.0'
    - run: npm ci
    - run: npm test
    - uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: 72695e617fccda44b14870493fa5a9ec39c091c8e3b06c6e90e46c87c241e62b
      with:
        coverageLocations: |
          ${{github.workspace}}/coverage/lcov.info:lcov